### ISSUE TITLE
Got error when running uart_send on windows

### ISSUE THREAD

**Issue by YuGu-OSS** [sony/pyAutoPort#3]
I got error when trying to run "uart_send ls" on windows.
The error log is:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\0000105341\AppData\Local\Programs\Python\Python311\Scripts\uart_send.exe\__main__.py", line 7, in <module>
  File "C:\Users\0000105341\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautoport\uart.py", line 63, in write_and_read_uart
    uart = serial.Serial(port=port, baudrate=baudrate, timeout=uart_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\0000105341\AppData\Local\Programs\Python\Python311\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\0000105341\AppData\Local\Programs\Python\Python311\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\0000105341\AppData\Local\Programs\Python\Python311\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '/dev/ttyUSB0': FileNotFoundError(2, 'The system cannot find the path specified.', None, 3)
```

**Comment by YuGu-OSS** [comment]
Prompt for 'UART port not found' is necessary
